### ISSUE TITLE
Test\es5: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by gusarov** [pavel-purma/vscode-mocha-test-runner#20]
I've opened test\es5 project and all tests are failed
TypeError: undefined is not a function

**Comment by CzBuCHi** [comment]
bug was introduced by PR #16 - incomplete config schema declaration... fixed in 0.3.3 .. (i hope)
